---
title: Home
---

::: {style="text-align: center;"}
![Image generated by ChatGPT[^about-the-image]](chisocnet-ergms-chatgpt-image.png){width="80%"}

[^about-the-image]: This image was generated using ChatGPT with the following prompt *'I am teaching an "Introduction to Exponential Random Graph Models" class (two-day) in a Chilean Summer school. I need you to help me create a figure that I can use for the homepage of the class website. The course looks at ERGMs applied using the R programming language. It has an emphasis on application (attendees will be using RStudio for running some models). This is in the context of a summer school about social network analysis'*
:::

Welcome to the second version of ChiSocNet's Summer School! This website was created for the ERGMs component of the school. Here, you will find three subpages with the following content: (1) Introduction to ERGMs, (2) Advanced ERGMs, and (3) New topics in Network Modeling.

# Disclaimer

This is an ongoing project. The course is being developed and will be updated as we go. If you have any comments or suggestions, please let me know. The generation of the course materials was assisted by AI tools, namely, GitHub copilot.

# Code of Conduct
  
Please note that the chisocnet-ss2024 project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/1/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.